<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="UTF-8" />
    <title>JS</title>
    <script>
      let error = (msg) => console.log(msg);

      function sum(a, b, err) {
        try {
          if (Number.isNaN(a) || Number.isNaN(b)) throw new Error();
          return a + b;
        } catch (e) {
          err("Были переданы некорректные параметры");
        } finally {
          console.log("Завершаем выполнение функции");
        }
      }

      let a = Number(prompt("Enter first number"));
      let b = Number(prompt("Enter second number"));
      console.log(sum(a, b, error));
    </script>
  </head>
  <body></body>
</html>

<!-- 1) Перепишите упражнение из предыдущего урока, но так, чтобы если пользователь ввёл некорректные данные, 
  то выбрасывалось исключение. И уже в блоке catch вызовите функцию error.
2) Добавьте блок finally, где выведите в консоль строку: «Завершаем выполнение функции». -->
